import type { Metadata } from "next";
import "../globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "../../components/dashboardHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <Sidebar />
      <main className="ml-64 flex-1 ">
        <div className="min-h-screen w-full bg-gray-50">
          <Header />
          {children}
        </div>
      </main>
    </div>
  );
}
